# -*- coding: utf-8 -*-
"""Копия блокнота "ChatBot_day1.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1abA0uC_SF9_gjcJEW197WofNl3BLEoUu
"""

import random
import nltk

"""## **Строки, списки и словари**

## **День 1**
"""

## Создаю бот-переменную, в которой буду хранить всю память моего бота – всю информацию, которая ему понадобится для работы
## Структурирую переменную в виде "словаря"
BOT_CONFIG = {
    'intents': {
        'hello': {
            'examples': ['Hello', 'Привет', 'Hi!', 'Здравствуйте'],
            'responses': ['Добрый день', 'Здравия желаю', 'Добрый вечер']
            },
        'bye': {
            'examples': ['пОкА', 'До свидания', 'Увидимся'],
            'responses': ['До связи', 'Саёнара', 'Чао']
            },
        'howdoyoudo': {
            'examples': ['как дела?', 'как жизнь?'],
            'responses': ['всё хорошо', 'Спасибо, хорошо', 'Не жалуюсь']
            }
      },
      'not_found': {
          'responses': ['Извините, не удалось определить интент', 'Я пока ещё глупый бот и ничего не понимаю']
      }
}

def clean(text):
  cleaned_text = ''
  for ch in text.lower():
    if ch in 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ':
      cleaned_text = cleaned_text + ch
  return cleaned_text

def get_intent(text):
  for intent in BOT_CONFIG['intents'].keys():
    for example in BOT_CONFIG['intents'][intent]['examples']:
      cleaned_example = clean(example)
      cleaned_text = clean(text)
      if nltk.edit_distance(cleaned_example, cleaned_text) / max(len(cleaned_example), len(cleaned_text)) < 0.4:
        return intent
  return 'not_found'

def bot(text):
  intent = get_intent(text)
  if intent != 'not_found':
    return random.choice(BOT_CONFIG['intents'][intent]['responses'])
  else:
    return random.choice(BOT_CONFIG['not_found']['responses'])

input_text = ''
while input_text != 'exit':
  input_text = input() 
  response = bot(input_text)
  print(response)